// <auto-generated />
namespace InvoiceManger.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class changesomepropertys : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changesomepropertys));
        
        string IMigrationMetadata.Id
        {
            get { return "202006192322211_changesomepropertys"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
